### PR TITLE
apiKey config

### PR DESCRIPTION
**Pull request by graphcon**
Currently, when setting apiKey by configuration file, it isn't recognized. This is corrected here.

### CODE REVIEW

**Comment by Edujugon** [comment]
Have you tried with the API method setApiKey?

**Comment by graphcon** [comment]
Yes, I did. That works well.

But I think this data is better located in a config file like ios certificate paths.

**Comment by Edujugon** [comment]
I didn't add the apiKey param to the config list because the initial idea was to use this package for sending notifications to more than 1 app. That's why I added that method (setApiKey) which can update the apikey value dynamically per each app.

Anyway, I'll think about it to integrate it to the current code.

**Comment by graphcon** [comment]
I see your point. For APN for example, you can set certificates in config, hence I thought that was the intention in FCM as well.

A developer can still set ApiKey by calling setApiKey if it is required to send more Apps.

**Comment by Edujugon** [comment]
Yeah! That's true :)

I'll implement it soon.

**Comment by Edujugon** [comment]
This functionality has been added from the last release v2.1.4.
you may refer to the following commit if required d3d4ed74a5b7f7cb56caf44d33123526350ed16d

**Pull request closed without merging**
