### PR TITLE
Laravel 6 support

### PR DESCRIPTION
**Pull request by apervikov**
I've made few modifications to add Laravel 6 support (#91), please review that, thank you!

### CODE REVIEW

**Comment by Edujugon** [comment]
Hi @apervikov ,

Thanks for this PR.

I was about to update the package to provide support to L6 but since you already took the time for this, let's continue on this PR.

I don't think there is a need to drop L5 support so what about keeping both L5/6 for the time being?

```
"illuminate/support": "~5.8.0||^6.0",
"illuminate/notifications": "~5.8.0||^6.0",
```

**Comment by apervikov** [comment]
> Hi @apervikov ,
> 
> Thanks for this PR.
> 
> I was about to update the package to provide support to L6 but since you already took the time for this, let's continue on this PR.
> 
> I don't think there is a need to drop L5 support so what about keeping both L5/6 for the time being?
> 
> ```
> "illuminate/support": "~5.8.0||^6.0",
> "illuminate/notifications": "~5.8.0||^6.0",
> ```

Thank you for feedback, you are right since Laravel 5.8 still supports. I will modify dependencies here

**Comment by Edujugon** [comment]
Cool,

I'll review/merge it as soon as I can.

**Comment by Edujugon** [comment]
@apervikov 
Thanks for your contribution.

**Comment by Edujugon** [comment]
Closes #91

**Pull request merged**
