### PR TITLE
Laravel 9 support

### PR DESCRIPTION
**Pull request by xHeinrich**

### CODE REVIEW

**Comment by mohamed-foly** [comment]
+1

**Comment by MajorasJack** [comment]
@Edujugon please can this be reviewed?

**Comment by ishieric** [comment]
+1

**Comment by ishieric** [comment]
@Edujugon please can this be reviewed?

**Comment by Teglgaard** [comment]
+1

**Comment by danbower** [comment]
@Teglgaard You can fork this repo, apply the above commits then reference it within your composer.json using the following:

`"edujugon/push-notification": "dev-master",`

```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/Teglgaard/PushNotification"
    }
```

**Comment by ajayfroiden** [comment]
+1

Please merge the repo

**Pull request merged**
