### PR TITLE
apn.php: avoid recursion on connection failure

### PR DESCRIPTION
**Pull request by cs-couture**
Currently when Apn.php attempts to connect to apple push services we
attempt to re-try caught exceptions if one is thrown.  However, in
situations where a push certificate is invalid or expired we run into
infinite recursion constantly re-trying the connection without providing
any feedback.

The following will set a limit on the number of times we may re-try.
Configurable if users defined 'connection_attempts'.

Signed-off-by: Jamie Couture <jamie.couture@crowdspark.com>

### CODE REVIEW

**Comment by Edujugon** [comment]
Hi @cs-couture ,

That definitely is a very good option to add to the config.
There are two things that we should think about in this new feature:
- Allow unlimited attempts (I would suggest so setting that value to `0`)
- connectionAttempts value should be reseted in those methods it's be used since if you were using the same object to send notifications, after the first try sending, the followings would have 0 extra attempts.

What do you think about the above points?

**Comment by cs-couture** [comment]
Sounds good to me.

Accounting for unlimited is fine, and I can update the documentation to point that out.  I would only argue it may not be sane to let it be unlimited by default, so as long as documentation points out it is limited, and must be marked unlimited.

As for resetting, I thought it would have been saner to do that too, but wasn't sure if we cared.  Since it sounds like we *should* care, I'll reset the counter after successful initial connection.

---

On a different note,  I branched from the earliest point of introduction in case you wanted to roll a patch release to the 2.x series.

In terms of updates, do you have a preference regarding my making the amended changes? New pull request with changes squashed already in some new branch, in my existing branch or just apply requested changes on top -- you can squash as you see fit.

I know some people can be particular about use of rebase.  I don't particularly care either way.  What would you prefer?

**Comment by cs-couture** [comment]
I've amended my branch to address existing points raised.  Do let me know if there's anything else you may like to see.

Cheers,

**Comment by Edujugon** [comment]
Hi @cs-couture . I'll have a look as soon as I get some free time.

Thank you :)

**Comment by cs-couture** [comment]
I also realized I forgot to include tests, so I've updated my branch to include some tests.

**Comment by Edujugon** [comment]
That's great! Thanks again @cs-couture

**Comment by cs-couture** [comment]
Ugh. Fixed a silly typo!

**Comment by Edujugon** [comment]
Hi @cs-couture ,
I've just merged your PR :)

Thanks for your contribution!!

**Pull request merged**
