### PR TITLE
Push notification channels

### PR DESCRIPTION
**Pull request by jenky**
Add Apn, Fcm, Gcm channels for [Laravel notifications](https://laravel.com/docs/5.5/notifications).

### CODE REVIEW

**Comment by Edujugon** [comment]
Hi @jenky ,
Thanks for your contribution, I like this new addition.
I'll have a look at the code and if everything looks fine I'll merge it.

**Comment by jenky** [comment]
Hi @Edujugon 

I think `extraDataName` is redundant because you have to format the payload in `buildData` anyway.

**Comment by Edujugon** [comment]
HI @jenky ,
Yes you are right, At the beginning I thought to move [this lines](https://github.com/jenky/PushNotification/blob/1a68870a6a9aa256398b5975e2cb180bd23e7799/src/Channels/ApnChannel.php#L32toL34) of each Channel classes to the parent so that's why I created that method. But it's better to leave it as it is now :)

One question, Did you test this feature? if so, on what Laravel versions have you tested it out?

**Comment by jenky** [comment]
Hi @Edujugon,

Sorry for the late response, I've been busy for the last few days. I tested this on Laravel 5.5 with `apn` channel, I'll try to set up `fcm` tomorrow.

Cheers, :nerd_face:

**Comment by Edujugon** [comment]
Thanks @jenky  :muscle:

**Comment by Edujugon** [comment]
Hi @jenky ,
I've just merged the PR and created a new release (3.0).
Update your composer.json to take the latest version, run in console:
`composer require edujugon/push-notification:"^3.0"`

Let me know if find any issue and again, thanks for your contribution 👍

**Comment by jenky** [comment]
@Edujugon 

Just tested with `fcm`, worked great. I'll update `3.0` on my dev environment and try it out.

Thanks, 👍

**Pull request merged**
